### ISSUE TITLE
Präambel haben ja/nein?

### ISSUE THREAD

**Issue by ledge8** [chaos-jetzt/verein#11]
Viele Vereine haben eine Präambel und ich fande soetwas auch cool

**Comment by n0th1ng-m4tt3r5** [comment]
Kannst ja mal ein PR machen, ansonsten können wir das für die zweite Version anpeilen.

**Comment by Proliecan** [comment]
Ich halte das für nicht notwendig.
Zeitfresser und Bikeshedding und so.

**Comment by teismar** [comment]
Das ist imo nicht nötig für chaos.jetzt und würde nur zu noch **mehr** Punkten führen, wo wir uns einigen müssten.
