### ISSUE TITLE
Weshalb sollte der Vorstand von §181 BGB befreit werden

### ISSUE THREAD

**Issue by septem9er** [chaos-jetzt/verein#13]
In der Satzung steht unter §7 Abs. 4

> Die Vorstandsmitglieder sind von der Vorschrift des § 181 BGB befreit.

Weshalb sollte der Vorstand Pauschal von dieser Regelung befreit werden? Wenn wäre es ohnhin nur relevant für die unter § 7b Abs. 2 genannten Punkte:

> Die geschäftsführenden Vorstandsmitglieder sind alleinvertretungsberechtigt. Ausgenommen sind
> - Einstellung und Entlassung von Angestellten,
> - gerichtliche Vertretung sowie Anzeigen,
> - Aufnahme von Krediten,
> - Erwerb, Belastung und Veräußerung von Grundstücken und Immobilien,
> - Gründung, Erwerb und Veräußerung von Gesellschaften sowie Geschäftsanteilen von Gesellschaften zur Verwirklichung der satzungsgemäßen Ziele.

Denn für alles andere gäbe es ja noch andere alleinvertretungsberechtigte Mitglieder des Vorstands die das Rechtsgeschäft abschließen könnten.

Zudem können andere Ausnahmen ja sonst auch per Beschluss der MV erfolgen.

**Comment by e1mo** [comment]
Man könnte darüber nachdenken, die Möglichkeit der Befreiumg vom § 181 BGB durch die MV explizit in der Satzung zu verankern. Formulierungsvorschlag dafür von [hier](https://paritaet-bw.de/leistungen-services/faq/vereinsrecht/beschraenkte-befreiung-von-den-voraussetzungen-des-ss-181-bgb-nach-den-vorgaben-von-aktion-mensch-oder-deutsches-hilfswerk-dhw):

> Für ein einzelnes Rechtsgeschäft können die vertretungsberechtigten Vorstandsmitglieder jeweils durch Beschluss der Mitgliederversammlung von den Beschränkungen des § 181 BGB befreit werden.

**Comment by Proliecan** [comment]
Da sollten wir BGB folgen.
