### ISSUE TITLE
Wort "grundsätzlich" entfernen

### ISSUE THREAD

**Issue by septem9er** [chaos-jetzt/verein#14]
Das Wort grundsätzlich bedeutet im juristischen Sinne, das Ausnahmen möglich sind. Im allgemeinen Sprachgebrauch verstehen Menschen dies jedoch oftmals so, dass keine Ausnahmen möglich sind. Daher sorgt das Wort in Satzungen regelmäßig für Missverständnise, weshalb ich das Wort entfernen würde.

In #5 wurde für eine Stelle in der das WOrt vorkommt bereits eine alternative Vorgeschlagen. Ansonsten kommt das Wort nur in §7 Abs. 3 vor:

> Die Vorstandsmitglieder sind grundsätzlich ehrenamtlich tätig; sie haben Anspruch auf Erstattung notwendiger und verhältnismäßiger Auslagen.

Hier wäre erstmal zu klären wie das denn gemeint ist. Sollen Ausnahmen von der Regelung möglich sein oder nicht? Wenn nicht würde ichd as Wort ersatzlos streichen, wenn ja würde ich spezifizieren unter welchen Umständen Ausnahmen möglich seien sollen. Wobei natürlich innerhalb der rechtlichen Möglichkeiten gearbeitet werden muss.

**Comment by teismar** [comment]
Merged
