### ISSUE TITLE
Beisitzende im Vorstand

### ISSUE THREAD

**Issue by septem9er** [chaos-jetzt/verein#15]
Aktuell sieht die Satzung 3-4 Vorstandsmitglieder vor, die alle Vorstand im Sinne des §26 BGB und alleinvertretungsbevollmächtigt sind.

chaos.jetzt könnte sich überlegen, ob es einen erweiterten Vorstand mit bis zu x Beisitzenden gibt, welche optional gewählt werden und nicht Vorstand im Sinne des §26 BGB sind. Dadurch wäre die größe des Vorstands flexibler, die Arbeit kann auf mehr Menschen aufgeteilt werden. Gleichzeitig können so neue Menschen in den Vorstand eingearbeitet werden ohne direkt Teil des Vorstands nach §26 GB zu sein.

**Comment by e1mo** [comment]
Ich wäre im Schritt eins auch dafür, die erste Satzung ohne eine solche Regelung zu haben.

Ob wir eine solche Regelung tatsächlich wollen / brauchen hängt für mich auch wieder davon ab, in welcher Rolle wir den Verein sehen bzw. die Arbeit des Vorstandes. Wenn der Vorstand lediglich verwaltend tätig seien soll halte ich es für Sinnvoll, diesen eher kleiner und Kompakter zu halten. So laufen wir nicht in das Problem, dass niemand sich so richtig zuständig fühlt sondern klar ist, wer sich zu kümmern hat.
Wenn der Vorstand in seiner Rolle als Vorstand jedoch auch gestaltend tätig werden soll, dann könnten Beiräte sicherlich eine Möglichkeit seien um die Arbeit des Vorstandes und diese Rolle zu unterstützen.

**Comment by Proliecan** [comment]
Ich stimme sowohl @n0th1ng-m4tt3r5, als auch @e1mo zu.

**Comment by teismar** [comment]
Same for me. Ich denke gerade momentan würde es einfach zu viel overhead an Arbeit und Prozessen führen.
