### ISSUE TITLE
Gemeinnützigkeit Ja/Nein/Etwas dazwischen?

### ISSUE THREAD

**Issue by ledge8** [chaos-jetzt/verein#8]
Ist es geplant, einen "gemeinnützigen" Verein  zu gründen? Falls ja, ist das relevant für den Vereinszweck etc..

**Comment by septem9er** [comment]
Selbst wenn sich dafür entschieden wird, dass der Verein erstmal nicht gemeinnützig sein soll, wäre es eine Überlegung Wert den Satzungszweck dennoch bereits so zu schreiben, dass eine gemeinnützigkeit möglich wäre.

**Comment by n0th1ng-m4tt3r5** [comment]
Bin auch für Gemeinnützigkeit nach Satzung, ob wir es steuerrechtlich durch bekommen oder nicht.
Ist ja auch schon vorgeschlagen in #2

**Comment by e1mo** [comment]
Ich wäre der Gemeinnützigkeit grundsätzlich auch offen, wäre aber auch fine damit wenn es kein Gemeinnütziger Verein wird.
Für mich schwingt da allerdings auch auch die Frage mit, wofür wir den Verein am Ende nutzen wollen. Also mal zu klären, wie viel (z.B. finanziellen) Nutzen wir durch die Gemeinnützigkeit gegenüber den Pflichten (Stichwort strengere Buchführungspflichten, restriktivere Mittelverwendung, Gefahr der Aberkennung) sehen.

**Comment by Proliecan** [comment]
Ich bin einer Gemmeinnützigkeit gegenüber offen eingestellt, aber halte es nicht zwingend für notwendig.

**Comment by Proliecan** [comment]
Entscheidung in Diskussion siehe Protokoll.
